### PR TITLE
Fixed tab background overlapping

### LINKED ISSUE #303: Tab padding overlaps
### What happened?

image-1
The area surrounding tabs overlaps. This is aesthetically displeasing

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.22

### Severity impact

Low, Enhancement

### What platform are you seeing the problem on?

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by n7itro**
Added bottom margin to tabs so tab backgrounds don't overlap with each other. Closes #303

### CODE REVIEW

**Comment by mauro-balades** [comment]
How does it look?

**Review by mauro-balades — CHANGES_REQUESTED** [review]
Don't add the important

**Comment by n7itro** [comment]
> How does it look?

Before:
image

After:
image

**Comment by mauro-balades** [comment]
Please remove the `important`

**Comment by mauro-balades** [comment]
Does it work without the `important` btw?

**Comment by n7itro** [comment]
> Does it work without the `important` btw?

When tested in the Browser Toolbox it requires `!important` but I'm not sure whether that applies here

**Comment by mauro-balades** [comment]
In the browser toolbox, in the same sector and file you added this one?

**Comment by n7itro** [comment]
I tested it in `userChrome.css`. By order of declaration this shouldn't require `!important`.
I will try testing it with this file instead

**Comment by n7itro** [comment]
I tested it in `vertical-tab.css` and it doesn't require it.

**Comment by mauro-balades** [comment]
Perfect, thanks a lot

**Pull request merged**
