### PR TITLE
Fixing HDR on MacOS, adding Prettier

### PR DESCRIPTION
**Pull request by HarryHeres**
Fixing https://github.com/zen-browser/desktop/issues/496

### CODE REVIEW

**Comment by HarryHeres** [comment]
@mauro-balades There's one issue - when the video is not fully visible (e.g. after scrolling), it switches to SDR mode. After being fully visible, HDR mode comes back. This is due to the `overflow: hidden` property, however I have not found an appropriate solution to that.

**Comment by mauro-balades** [comment]
I use clip-path because the website may overlap the border-radius

**Comment by HarryHeres** [comment]
> I use clip-path because the website may overlap the border-radius

I tried to implement a lot of various little workarounds that would enable the clip-path attribute to stay, but I was, unfortunately, unsuccessful :/

**Comment by mauro-balades** [comment]
You could use https://zen-browser.app/themes/c6813222-6571-4ba6-8faf-58f3343324f6

**Comment by HarryHeres** [comment]
I will try to look for and implement a different solution then. Closing this for now.

**Pull request closed without merging**
