### PR TITLE
resistFingerprinting

### PR DESCRIPTION
**Pull request by Unchanged4352**
It works this way right?

### CODE REVIEW

**Comment by mr-cheffy** [comment]
We won't enable this flag

**Comment by Unchanged4352** [comment]
> We won't enable this flag

Why?

**Comment by mr-cheffy** [comment]
It can break sites and not only that, but you LOCKED the preference

**Comment by Unchanged4352** [comment]
> It can break sites and not only that, but you LOCKED the preference

ok thanks

**Pull request closed without merging**
