### PR TITLE
Fixed URL Bar Border Radius and Padding

### LINKED ISSUE #1628: Tracking Shield Container is not aligned with other Icons and some other design issues
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?
Screenshot 2024-09-23 192028

1. The tracking shield container is not aligned with the other icons and seems off.
2. The border radius between toolbar icons and url bar doesn't seem consistent.
3. Padding on block is inconsistent with inline padding.
4. ... (Will be updating some more design issues)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

 1.0.1-a.3

### What platform are you seeing the problem on?

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by shetty-tejas**
Fixes #1628.

Before:
image

After:
image

### CODE REVIEW

**Comment by shettytejas** [comment]
@mauro-balades I was not able to test it locally due to some package breaking (I did it from userChrome.css tho). Could you just build it and check if everything looks fine? I will try to do one round of testing from my end tomorrow too, but if you could, that'd be great!

**Comment by mauro-balades** [comment]
I wont merge it for this release as im in kind of a hurry but will for the next one, thanks!

**Comment by shettytejas** [comment]
@mauro-balades no worries man! Thanks for the great work! You can take your time with merging this. If I find any other issues, I will fix them in the same PR.

**Comment by KarimElsayad247** [comment]
Is this a problem only on windows? On linux it looks fine for me
image
image

**Comment by mauro-balades** [comment]
It also looks good from my side, I dont really know what this PR is trying to fix

**Pull request closed without merging**
