### PR TITLE
Temporary logo color change

### PR DESCRIPTION
**Pull request by Donnnno**
Hi!

We talked about this a bit on Discord, but wanted to give you the choice too.

This is a temporary logo change, till we have a new one! 

Using a colored background can result in looking less like a certain military logo, and look actually friendlier to use. 

image

image

### CODE REVIEW

**Comment by AvinashK13** [comment]
I'm not aware of the discussion going on but the bg colour is horrendous!
Can we change the colour to something darker scheme pls?

**Comment by Donnnno** [comment]
@AvinashK13 There are plans to make a new logo, and lots of submissions are already made on the Discord server.
However, that probably takes a while before it's here.

This color is actually part of one of the Zen base colors we have since the start

image

**Comment by Anthonyy232** [comment]
It would probably be better to just wait.. multiple rebranding isn't exactly a good idea due to confusion

**Comment by mauro-balades** [comment]
@Donnnno could we add it just for Zen Twilight branch?

**Comment by Donnnno** [comment]
Done @mauro-balades 

I also made the gap a bit bigger in between the shapes.

**Comment by mauro-balades** [comment]
Great, thanks!

**Pull request merged**
