### PR TITLE
Add horizontal Tabs

### PR DESCRIPTION
**Pull request by bw8686**
This requires 1 new strings for settings (that is if you choose to keep the setting there)
`zen-vertical-tabs-button` which could be "Vertical Tabs"

Feel free to edit to fit zen's settings page.

### CODE REVIEW

**Comment by bw8686** [comment]
This is good to merge now if you are ok with the settings and stuff like that.

**Comment by bw8686** [comment]
me when the github mobile app is total garbage and sends my comment twice

**Comment by mauro-balades** [comment]
Ill merge it once it's 100% implemented, there seems to be issues with pinned tabs

**Comment by bw8686** [comment]
this can be checked out now

**Comment by Neintonine** [comment]
Hei, could you perhaps squash the commits to one commit? That would clear up the commit log, once the PR is merged. ;)

**Comment by mauro-balades** [comment]
You (I) can squash and merge directly from the PR

**Comment by 3kh0** [comment]
Please merge this as I the vertical tabs to be the only reason that I do not main zen browser. :D

**Comment by alexjsteffen** [comment]
Yes, I am also patiently waiting for this feature!

**Comment by mauro-balades** [comment]
Not as easy...

1. The implementation is pretty bad (it uses absolute values, it may not work if UI changes or screen size changes)
2. My current plans aren't really helping with horizontal tabs (Tree style view)
3. Some things still dont work (like scrolling pinned tabs)

**Comment by FrostedVolcano** [comment]
Yes please.

**Comment by B1ack3ye** [comment]
Any updates on this?

**Comment by p0358** [comment]
Personally for the time being Sidebery with auto-hiding sidebar seems to be a really nice connection. That extension has the most features, is snappy, though sadly doesn't support some Zen-specific things like triggering tab splitting

**Comment by AvinashK13** [comment]
Loving the browser so far 👏🏼
Hope horizontal tabs gets implemented soon

**Comment by B1ack3ye** [comment]
> Zen Browser will not support horizontal tabs in the near future. The decision to focus on Vertical Tabs is a core design choice, with the entire Zen Browser experience built around this concept. This approach is intended to maximize screen space and improve navigation, making vertical tabs an essential part of Zen’s philosophy.

That's disappointing to hear. The browser really had great potential for me, and it was finally a Firefox fork that genuinely surprised me and made me consider using it as my main browser.
Now that horizontal tabs won't be implemented anytime soon, and it sounds like they likely never will due to Zen's philosophy, it's probably time for me to look elsewhere for a good browser.

**Comment by probablykasper** [comment]
For me, horizontal tabs would maximize screen space and improve navigation so I hope it could be considered

**Comment by alexjsteffen** [comment]
Please see my comment [here](https://github.com/zen-browser/desktop/discussions/889#discussioncomment-10786366) about an alternative proposal for horizontal tabs.

**Comment by gustavoabel** [comment]
Any updates?

**Comment by Tunisia911** [comment]
It is really disappointing that Zen browser is restricting us to vertical tabs.
I was really excited about trying it, I love the look, feeling and the features (like workspaces) of this "futuristic" browser.
However, after downloading it I was surprised by the lack of an option to enable horizontal tabs. Now, I am shocked since I found the concept already published on github, ready to use, but they just deny the idea that a lot of users (most of them actually) are used to horizontal tabs and do not want to change. Moreover, most browsers have it as their default layout which made it the established norm among users.
I hope they add this mod as a Zen Mod since it will absolutely be crucial in their competition against other browsers.
I find the Zen browser's stand disappointing since I thought that it will be my new main browser.
I am not considering Zen ever again until they implement this feature.

**Comment by Tunisia911** [comment]
It is really disappointing that Zen browser is restricting us to vertical tabs.
I was really excited about trying it, I love the look, feeling and the features (like workspaces) of this "futuristic" browser.
However, after downloading it I was surprised by the lack of an option to enable horizontal tabs. Now, I am shocked since I found the concept already published on github, ready to use, but they just deny the idea that a lot of users (most of them actually) are used to horizontal tabs and do not want to change. Moreover, most browsers have it as their default layout which made it the established norm among users.
I hope they add this mod as a Zen Mod since it will absolutely be crucial in their competition against other browsers.
I find the Zen browser's stand disappointing since I thought that it will be my new main browser.
I am not considering Zen ever again until they support this feature.

**Comment by gustavoabel** [comment]
> It is really disappointing that Zen browser is restricting us to vertical tabs. I was really excited about trying it, I love the look, feeling and the features (like workspaces) of this "futuristic" browser. However, after downloading it I was surprised by the lack of an option to enable horizontal tabs. Now, I am shocked since I found the concept already published on github, ready to use, but they just deny the idea that a lot of users (most of them actually) are used to horizontal tabs and do not want to change. Moreover, most browsers have it as their default layout which made it the established norm among users. I hope they add this mod as a Zen Mod since it will absolutely be crucial in their competition against other browsers. I find the Zen browser's stand disappointing since I thought that it will be my new main browser. I am not considering Zen ever again until they support this feature.

use https://www.diabrowser.com/ my bro.

**Comment by AmeerArsala** [comment]
Someone pls finish this feature

**Pull request closed without merging**
