### PR TITLE
Feature: Pinned Tab URL Reset & Base URL Persistence

### PR DESCRIPTION
**Pull request by kristijanribaric**
This PR introduces functionality to reset a pinned tab back to its originally pinned URL. Two methods are available for resetting:

1. **Context Menu**: Use the "Reset Pinned Tab" option from the context menu.
2. **Keyboard Shortcut**: Pressing `CTRL + W` (or whatever you mapped it to) to close the tab will unload the pinned tab and reset it to the originally pinned URL (if this option is enabled in the settings).

Additionally, the default behavior for closing a pinned tab using the `CTRL + W` shortcut has been updated. It now unloads the tab and switches to the next available tab.

Related to:
https://github.com/zen-browser/l10n-packs/pull/63
https://github.com/zen-browser/components/pull/35

https://github.com/user-attachments/assets/d5e7ad73-2ea5-464d-856d-a552b655fbda

### CODE REVIEW

**Comment by n7itro** [comment]
Closes https://github.com/zen-browser/desktop/discussions/1453

**Comment by Hikiru** [comment]
In the meantime, could you implement this as a mod? Also, ctrl+w behavior should also reset the pinned tab after unloading, similar to Arc. Does this fix layout getting switched too? For instance, if I have YouTube in the third slot, open it, then restart Zen, YouTube will move to the first slot. Really annoying to me

**Comment by kristijanribaric** [comment]
Not really possible to turn it in a mod as it's deeply integrated into the browser's source code, sry.

**Comment by mauro-balades** [comment]
Im going to close this, because I dont like it's inside the tab unloader code... We should move it into it's own functionality

**Pull request closed without merging**
