### PR TITLE
windows icons fix

### PR DESCRIPTION
**Pull request by Donnnno**
This should fix the icons for windows, including .ico's for every resolution.

I've also added an incognito icon and icons for the pdf and web files:

image

image

The new icons should probably be mapped to make it work, but I don't know how.

MacOS and Linux will come later.

### CODE REVIEW

**Comment by mauro-balades** [comment]
<3

**Comment by mauro-balades** [comment]
wait, what's [pbmode.ico](https://github.com/zen-browser/desktop/pull/357/commits/0c3930425ad65feaccc806abfafe6e18402293cf#diff-17c835b9820556d4ac56b4788def39d591f920cf489bcebef141c87e8e8ac856)?

**Comment by mauro-balades** [comment]
we also need a firefox64.ico

**Comment by mauro-balades** [comment]
https://searchfox.org/mozilla-central/source/browser/branding/nightly/firefox64.ico

**Comment by Donnnno** [comment]
ff64 is already in there, right? 

found pbmode inside the floorp repo, it's called private browsing

**Comment by mauro-balades** [comment]
> ff64 is already in there, right?

oh, it doesn't need a fix?

**Comment by Donnnno** [comment]
fixed 64

**Comment by mauro-balades** [comment]
[content/windows](https://github.com/zen-browser/desktop/pull/357/commits/0c3930425ad65feaccc806abfafe6e18402293cf#diff-008dcaa305da4e46fbb1cfba8cfbac6132f25bad3ab1bb529e5d9e1efdc710d0) doesnt have the icons inserted?

**Pull request merged**
