### PR TITLE
Exposes Letterboxing https://github.com/zen-browser/desktop/issues/475

### PR DESCRIPTION
**Pull request by gunir**
Exposes Letterboxing https://github.com/zen-browser/desktop/issues/475

### CODE REVIEW

**Comment by mauro-balades** [comment]
Just to be sure, this doesnt enable it, right? it just exposes

**Comment by gunir** [comment]
> Just to be sure, this doesnt enable it, right? it just exposes

Of course, it's false

**Comment by qtchaos** [comment]
Don't see why this shouldn't be merged, if Zen is supposed to be as customizable as possible and also privacy focused, then simply exposing the config option doesn't do any harm.

**Comment by mauro-balades** [comment]
Yeah, I was just making sure, haha

**Pull request merged**
