### PR TITLE
Update dependencies, fix CI, use our own free disk space script

### PR DESCRIPTION
**Pull request by larziwau**
Updates dependencies and fixes something I forgot about the CI. Also uses a better script for cleaning up space (which is faster and empties more space, ALSO ITS LOCAL, means we no longer need to download the action and waste time.)

### CODE REVIEW

**Comment by larziwau** [comment]
Also I did setup dependabot for dependencies (runs weekly, can be modified to run monthly)

**Comment by larziwau** [comment]
Btw thanks to https://github.com/rust-lang/rust/pull/134151

**Comment by mr-cheffy** [comment]
Sorry but a lot of versions here are changed and we dont really need our own disk freeing script. Sorry

**Comment by larziwau** [comment]
Okay thanks for interest though

**Pull request closed without merging**
