### PR TITLE
Style: make the URL bar more rounded

### PR DESCRIPTION
**Pull request by RetrogradeDev**
Switch the border radius from 6px to 10px.
image

### CODE REVIEW

**Comment by Anthonyy232** [comment]
Shouldn't this be a CSS mod as it is personal taste?

**Comment by RetrogradeDev** [comment]
> Shouldn't this be a CSS mod as it is personal taste?

If mods can have some type of settings page, then I could do that, but this makes it look way more native on MacOS and Windows (and the most Linux distros)

**Comment by cheeeebs** [comment]
> > Shouldn't this be a CSS mod as it is personal taste?
> 
> If mods can have some type of settings page, then I could do that, but this makes it look way more native on MacOS and Windows (and the most Linux distros)

Mods can have preferences, yes.

**Comment by RetrogradeDev** [comment]
> > > Shouldn't this be a CSS mod as it is personal taste?
> 
> > 
> 
> > If mods can have some type of settings page, then I could do that, but this makes it look way more native on MacOS and Windows (and the most Linux distros)
> 
> 
> 
> Mods can have preferences, yes. 

Could you send me the link to the docs please? The documentation I found was pretty incomplete.

**Comment by GunGunGun** [comment]
> > > > Shouldn't this be a CSS mod as it is personal taste?
> > 
> > 
> > > 
> > 
> > 
> > > If mods can have some type of settings page, then I could do that, but this makes it look way more native on MacOS and Windows (and the most Linux distros)
> > 
> > 
> > Mods can have preferences, yes.
> 
> Could you send me the link to the docs please? The documentation I found was pretty incomplete.

Learning from other mods is fastest way to write your own:
https://github.com/JLBlk/Zen-Themes/tree/main/SuperGradient

**Comment by RetrogradeDev** [comment]
> > > > > Shouldn't this be a CSS mod as it is personal taste?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > If mods can have some type of settings page, then I could do that, but this makes it look way more native on MacOS and Windows (and the most Linux distros)
> > > 
> > > 
> > > Mods can have preferences, yes.
> > 
> > 
> > Could you send me the link to the docs please? The documentation I found was pretty incomplete.
> 
> Learning from other mods is fastest way to write your own: https://github.com/JLBlk/Zen-Themes/tree/main/SuperGradient

Thanks a lot, I also found the right docs.

**Pull request merged**
