### PR TITLE
Added AppImage installation option to README

### PR DESCRIPTION
**Pull request by ruanfdev**
This PR enhances the organization and clarity of the Linux installation instructions by:

- Adding a clear "Linux" main section header
- Organizing content into subsections:
  1. Arch-based distributions
  2. Other Linux distributions (AppImage)

This structure makes it easier for users to find installation instructions relevant to their Linux distribution and highlights the availability of the AppImage option with automated system integration.

No functional changes were made - this is purely a documentation improvement for better readability and organization.

### CODE REVIEW

**Comment by mr-cheffy** [comment]
These extra downloads are supposed to be for those that don't appear on the site

**Comment by ruanfdev** [comment]
I understand, this script just makes it a whole lot better to have the AppImage automated which allows users to skip the manual installation of the AppImage. Maybe we can keep it just until we can add Zen to the different repositories for example APT repo like with AUR for Arch.

**Comment by ruanfdev** [comment]
@mauro-balades Please see my initial comment as well here - https://github.com/zen-browser/desktop/commit/85017433db25f1616949e4a73ca6bbcfb8bbc46a#commitcomment-147992725

**Comment by mr-cheffy** [comment]
Thanks!

**Pull request merged**
