### PR TITLE
Add discord notification 🚨

### PR DESCRIPTION
**Pull request by NOCanoa**
this action will run after a release and will ping all the users whit the update role
U need to add this -> ${{ secrets.DISCHOOK }} ,secret and add the web-hook link for the announcements Chanel

image

### CODE REVIEW

**Comment by mauro-balades** [comment]
I think we should merge it into the release-alpha workflow

**Comment by NOCanoa** [comment]
u tell me, i did it as diferent workflow because i didnt want to interfere in the main workflow 🤷‍♂️, but we could also add more off them so in #github-build chanel there could be info related to the build steps (start end time)?

**Comment by NOCanoa** [comment]
If u merge now we will get a ping in discord for this release 👀

**Comment by NOCanoa** [comment]
if u dont manage to make ur release notes scrip to send to discord, merge this before and when u done then u can remove this again

**Comment by mauro-balades** [comment]
im working on a different way of doing this rn

**Comment by NOCanoa** [comment]
> im working on a different way of doing this rn @mauro-balades 

Hmm how so ? 👀

**Pull request closed without merging**
