### PR TITLE
Adding Homebrew 

### PR DESCRIPTION
**Pull request by HarryHeres**
This PR adds Homebrew Cask for the Zen Browser in order to be able to install the browser from command line. The "tap" is self hosted, pointing at this repository. 

The automatic update of the Cask version for new releases remains yet to be tested.

Also, macOS users installing via Homebrew will not be prompted that the application is damaged.

### CODE REVIEW

**Comment by mauro-balades** [comment]
Hi, thanks a lot! 

Could the scripts moved to the `scripts/` folder? Also, how would updates work?

**Comment by mauro-balades** [comment]
And the workflow, it should be separated (like where `flatpak` is, in order to avoid updating the repo if something failed on another build like windows)

**Review by mauro-balades — CHANGES_REQUESTED** [review]
I've commented the changes I requested

**Comment by HarryHeres** [comment]
> Hi, thanks a lot!
> 
> Could the scripts moved to the `scripts/` folder? Also, how would updates work?

As for the updates - on `brew install`, the browser version specified in the `version` attribute in `zen-browser.rb` will be installed. When a user executes `brew upgrade zen-browser`, the `livecheck` procedure will be performed. If new version is found in GitHub releases, it will be downloaded and installed accordingly. 

To ensure that the latest version is installed on `brew install` command, there's the update script included. 

PS: I'm no expert in Homebrew, but all of this was created by consulting their official docs :)

**Comment by HarryHeres** [comment]
> Hi, thanks a lot!
> 
> Could the scripts moved to the `scripts/` folder? Also, how would updates work?

If you want, I can definitely move the script into the `scripts` folder, however I thought that it could be a part of the `.github` folder as it should be executed only by the pipeline(s)?

**Comment by mauro-balades** [comment]
> > Hi, thanks a lot!
> > Could the scripts moved to the `scripts/` folder? Also, how would updates work?
> 
> If you want, I can definitely move the script into the `scripts` folder, however I thought that it could be a part of the `.github` folder as it should be executed only by the pipeline(s)?

In that case, you can store it inside `.github/workflows/src/` with the other scripts

~ mauro




Sep 1, 2024, 19:32 by ***@***.***:

**Comment by HarryHeres** [comment]
@mauro-balades Updated based on your comments. Make sure to check out the workflow changes if they're correct :)

**Comment by mauro-balades** [comment]
I think we can push directly instead of making a PR, no?

**Comment by HarryHeres** [comment]
Sure, I also would prefer it that way but noticed that you create a PR with flatpaks so I figured I would leave it the same. But if you're okay with it, we can change it to pushing immediately to master.

**Comment by mauro-balades** [comment]
I've already changed it, let me review if everything ok, and then we should be ready to go!

**Review by mauro-balades — APPROVED** [review]

**Pull request merged**
