### PR TITLE
Fix vertical tabs on the right overflow.

### LINKED ISSUE #1073: Right vertical hidden tabbar goes out of screen bounds
### What happened?

Tab bar is extends out of screen and is not shown fully when compact mode is active and Tabs on right is active .
This behavior doesn't occur on left side.
image
floating urlbar and minimal sidebar components are installed

Windows 10

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by damianfijorek**
Fix #1073. The `vbox` overflows the parent `#navigator-toolbox`. It's fine for tabs on the left but when they are on the right the overflow is out of the window/screen as described in the issue. With `float: right` the `vbox` overflows to the left and is fully visible and has the same distance to the window edge.

### CODE REVIEW

**Comment by mauro-balades** [comment]
You are a live saver!

I was about to give up and then saw this PR, thanks!!!

image

**Comment by Azathoth-X** [comment]
still doesnt work for me with expanded tabs collapsed tabs work fine though
here is with diff settings:
- collapsed:
image
- default expand
image
- exapnd on hover ( overflows to left ik doesnt work in compact but weird behavior)
image

on Zen Browser 1.0.0-a.34 (20240830230617)

**Comment by damianfijorek** [comment]
I reproduced and tried to fix only compact mode in this PR.

**Comment by damianfijorek** [comment]
I've installed latest version and the issue is still there. I checked here and my changes were not merged. There was merge that resulted in 0 changes.

image

**Pull request merged**
