### PR TITLE
smaller minimum sidebar width

### PR DESCRIPTION
**Pull request by n7itro**
Give users greater freedom of customization

### CODE REVIEW

**Comment by mauro-balades** [comment]
Sorry man, but im not going to accept this :(

if they want it smaller, collapse it. If it goes below this value, things will start to overlap, and I dont want to deal with it.

**Comment by n7itro** [comment]
> Sorry man, but im not going to accept this :(
> 
> if they want it smaller, collapse it. If it goes below this value, things will start to overlap, and I dont want to deal with it.

I tried it and nothing was overlapping or bugged. If it does overlap, then they can just make it wider

**Comment by mauro-balades** [comment]
Theme moment?

**Comment by n7itro** [comment]
image
For reference, this is what it looks like at 100px width.
I could make a compact sidebar theme...

**Comment by n7itro** [comment]
I will make it a theme.

**Pull request closed without merging**
