### PR TITLE
Support URL to FAQ - 2nd Try 🐷

### PR DESCRIPTION
**Pull request by GunGunGun**
🐷

image

### CODE REVIEW

**Comment by mr-cheffy** [comment]
🐷

**Comment by GunGunGun** [comment]
> 🐷

🐷

**Comment by Shockshwat** [comment]
Do you know why preferences was appended to the end of it? I tried finding it but i couldn't find a single reference of any support url in the codebase.

**Comment by GunGunGun** [comment]
> Do you know why preferences was appended to the end of it? I tried finding it but i couldn't find a single reference of any support url in the codebase.

Spaghetti codebase, probably 🐷

**Pull request merged**
