### PR TITLE
Fixes Rounded corners broken with Zen Dream and Zen Galaxy

### PR DESCRIPTION
**Pull request by JLBlk**
- Possible fix for #1508

### CODE REVIEW

**Comment by BrhmDev** [comment]
Seems to work.

**Comment by mauro-balades** [comment]
Dream and galaxy has been removed from zen in the next release... Sorry

**Comment by mussashii** [comment]
> Dream and galaxy has been removed from zen in the next release... Sorry 

Why not making an option at least, man? Some people like it. It was my fav theme and I had no problem with it. Thank you for your effort, and I hope that you bring it back.

**Comment by BowDown097** [comment]
> Dream and galaxy has been removed from zen in the next release... Sorry

sad!

**Pull request closed without merging**
