### PR TITLE
Don't reload sidepanel browsers when not needed

### PR DESCRIPTION
**Pull request by Eragonfr**
This fix the issue of the side panel being reloaded when it is toggled on/off and pinned/unpinned

### CODE REVIEW

**Comment by mr-cheffy** [comment]
What about the layout issues?

**Comment by Eragonfr** [comment]
> What about the layout issues?

Which ones ?

**Comment by mr-cheffy** [comment]
Like, have you tested this? Does dragging unpinned sidebar allow it to overflow it's parent?

**Comment by Eragonfr** [comment]
I can drag the unpinned sidebar like that
image

To me it seems to behave the same as in 1.0.1-a.19 with the reload on toggle being fixed.

I don't see any issue with the layout.

**Comment by mr-cheffy** [comment]
Can you drag the sidebar out of bounds? That's what im asking.. sorry for being so annoying haha

**Comment by Eragonfr** [comment]
Like over the tab bar ? Or the top bar ?
No, you can't.
I made sure that it was behaving the same as before.
If you want to allow it to hover the tab bar it's quite an easy change (remove one line)

You're not annoying, but I had an hard time to understand what you meant.

**Comment by mr-cheffy** [comment]
> but I had an hard time to understand what you meant

Sorry haha, im bad at english, worse at understanding.

Thanks a lot!

**Pull request merged**
