### PR TITLE
Hide Toolbar button in customize mode to reduce user confusion

### PR DESCRIPTION
**Pull request by Richard-Woessner**
This isnt an issue but wanted to give mauro-balades the option to add this after merging PR I-2676, because they are similar issues

image

image

### CODE REVIEW

**Comment by Richard-Woessner** [comment]
# Update

## Before
image

## After
image

**Comment by mr-cheffy** [comment]
Why make a patch when you can just add it to `zen-single-components.css`?

**Comment by Richard-Woessner** [comment]
Sorry I didn't know that was a choice. Ill adjust it today

**Comment by Richard-Woessner** [comment]
Sorry I didnt know that was a choice. Ill adjust it today

**Comment by Richard-Woessner** [comment]
@mauro-balades Fixed, and Ill take note to use those css files for cases like these from now on

**Comment by mr-cheffy** [comment]
Thanks!

**Pull request merged**
