### PR TITLE
Feature: Workspace reordering

### PR DESCRIPTION
**Pull request by kristijanribaric**
This PR introduces a new reorder mode to the Workspaces panel, allowing users to easily rearrange their workspaces. The following changes were made:

- Added a "reorder mode" toggle button to the Workspaces panel.
- Implemented functionality to enable/disable reorder mode.
- Updated the Workspaces panel to display "grab indicator" when reorder mode is enabled
- Added visual cues to indicate the current active workspace and reorder mode status.

These changes enhance the usability of the Workspaces panel by providing a convenient way to manage and organize workspaces.

Depends on:
https://github.com/zen-browser/l10n-packs/pull/77
https://github.com/zen-browser/components/pull/54

https://github.com/user-attachments/assets/89734eef-ab48-4b68-9b97-8ff12fe62ad6

### CODE REVIEW

**Comment by darkvergus** [comment]
Wouldn't a drag and drop work better?

**Comment by nanoraptor** [comment]
> Wouldn't a drag and drop work better?

was thinking the same

**Comment by kristijanribaric** [comment]
I heard you guys... PR has been updated with drag based reordering

**Comment by mr-cheffy** [comment]
Great! Thanks a lot!

**Pull request merged**
