### PR TITLE
Refactor sidebar expanded on-hover functionality and fix sidebar expa…

### PR DESCRIPTION
**Pull request by Richard-Woessner**
…nd/collapse behavior

- **Preferences**:
  - Added a new preference `zen.view.sidebar-expanded.on-hover.paused-for-expand` to manage the paused state of the sidebar hover functionality.
  - Updated `zen.view.sidebar-expanded.on-hover` preference handling to ensure proper behavior when toggling the sidebar.

- **ZenUIManager.mjs**:
  - Updated `_updateOnHoverVerticalTabs` method to handle the expanded state and remove hover attributes when the sidebar is expanded.
  - Refactored `_updateEvent` method to check and handle the expanded state of the sidebar, and to open or close the sidebar accordingly.
  - Added `openSidebar` and `closeSidebar` methods to manage the sidebar's expanded state and related attributes.
  - Refactored `toggleExpand` method to handle the new `paused-for-expand` preference and ensure proper toggling of the sidebar's expanded state.

- **zen-settings.js**:
  - Updated `setCompactModeStyle` method to handle the new `paused-for-expand` preference.
  - Ensured that the `paused-for-expand` preference is reset when the sidebar expand strategy is changed.

- **zen-browser.js**:
  - Added the new preference `zen.view.sidebar-expanded.on-hover.paused-for-expand` with a default value of `false`.

- **Submodule Updates**:
  - Updated `l10n` submodule to the latest commit `dd93803b84f398834049a3f650536fbdbd14cbca`.
  - Updated `zen-components` submodule to the latest commit `d853fa8de4167dfd4d1289f4f15792a698c738c3-dirty`.

- **Miscellaneous**:
  - Fixed indentation issues in `ZenUIManager.mjs`.
  - Removed commented-out code in `ZenUIManager.mjs`.
  - Ensured proper formatting and alignment of code blocks.

ISSUE: #2156

## Summary by CodeRabbit

- **New Features**
	- Introduced a preference for sidebar expansion behavior in Zen Marketplace settings.
	- Enhanced theme management with improved visibility handling for dark theme styles.
	- Improved keyboard shortcut management with conflict checks and reset confirmation.

- **Bug Fixes**
	- Corrected event listener handling for theme toggles to better reflect user preferences.

- **Refactor**
	- Updated variable declarations for improved scoping in sidebar management.
	- Adjusted logic for sidebar expansion behavior to ensure correct default settings.

### CODE REVIEW

**Comment by Richard-Woessner** [comment]
https://github.com/user-attachments/assets/b3d1fbf0-3652-44ba-90a4-67bae3a3bc25

**Comment by Anthonyy232** [comment]
Any chance of an animation when it is sliding back in? I remember a PR for that a while back but seems like it got closed..

**Comment by Richard-Woessner** [comment]
Ya I messed up this pr so it closed so it hasn't been merged yet

**Comment by mr-cheffy** [comment]
Thanks a lot!

**Pull request merged**
